# Usa una imagen base mínima de Linux
FROM docker.io/library/debian:bullseye-slim

# Establece variables de entorno para NVM
ENV NVM_DIR=/root/
ENV NODE_VERSION=v20.15.0

# Instala las dependencias necesarias
RUN apt-get update && apt-get install -y \
    curl \
    wget \
    build-essential \
    && rm -rf /var/lib/apt/lists/*

# Instala NVM, Node.js, y PNPM
RUN curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.7/install.sh | bash \
    && . $NVM_DIR/nvm.sh \
    && nvm install $NODE_VERSION \
    && nvm use $NODE_VERSION \
    && nvm alias default $NODE_VERSION \
    && wget -qO- https://get.pnpm.io/install.sh | ENV="$HOME/.bashrc" SHELL="$(which bash)" bash -

# Añadir NVM, Node y PNPM al PATH
ENV NODE_PATH $NVM_DIR/v$NODE_VERSION/lib/node_modules
ENV PNPM_PATH /root/.local/share/pnpm:/usr/local/share/pnpm
ENV PATH      $NVM_DIR/v$NODE_VERSION/bin:$PNPM_PATH:$PATH

# Directorio de trabajo
WORKDIR /root/app
