apiVersion: v1
kind: Pod
metadata:
  name: larapod
spec:
  containers:
    - name: mysqlcontainer #Mysql
      image: docker.io/library/mysql:8.0
      args: mysqld
      env:
        - name: MYSQL_ROOT_PASSWORD
          value: root_password
        - name: MYSQL_DATABASE
          value: laravel_db
        - name: MYSQL_USER
          value: laravel_user
        - name: MYSQL_PASSWORD
          value: laravel_password
      ports:
        - containerPort: 3306
          hostPort: 33060
      volumeMounts:
        - mountPath: /var/lib/mysql
          name: db-data

    - name: mailpitcontainer #Mailpit
      image: docker.io/axllent/mailpit:latest
      ports:
        - containerPort: 8025
          hostPort: 80250

    - name: phpcontainer #PHP
      image: php-fpm-image:latest
      args:
        - php-fpm
      volumeMounts:
        - mountPath: /var/www/html
          name: code-data

    - name: nginxcontainer #Nginx
      image: nginx-image:latest
      args:
        - nginx
        - -g
        - daemon off;
      ports:
        - containerPort: 80
          hostPort: 8000
        - containerPort: 443
          hostPort: 4430
      volumeMounts:
        - mountPath: /var/www/html
          name: code-data

    - name: nodecontainer # NodeJs
      image: node-image:latest
      ports:
        - containerPort: 5173
          hostPort: 51730
      volumeMounts:
        - mountPath: /var/www/html
          name: code-data

    - name: redis # Redis
      image: docker.io/library/redis:latest
      ports:
        - containerPort: 6379
          hostPort: 6379

  volumes:
    - name: db-data
      hostPath:
        path: ~/projects/project/mysql
    - name: code-data
      hostPath:
        path: ~/projects/project
        type: Directory
