# Save the output of this file and use kubectl create -f to import
# it into Kubernetes.
#
# Created with podman-5.1.1
apiVersion: v1
kind: Pod
metadata:
  annotations:
    io.kubernetes.cri-o.SandboxID/mailpitcontainer: 09235d81dc8513fc3f51b604a9ef249b76a5178e4ff1fd8063ff0f5d05503e21
    io.kubernetes.cri-o.SandboxID/mysqlcontainer: 09235d81dc8513fc3f51b604a9ef249b76a5178e4ff1fd8063ff0f5d05503e21
    io.kubernetes.cri-o.SandboxID/nginxcontainer: 09235d81dc8513fc3f51b604a9ef249b76a5178e4ff1fd8063ff0f5d05503e21
    io.kubernetes.cri-o.SandboxID/phpcontainer: 09235d81dc8513fc3f51b604a9ef249b76a5178e4ff1fd8063ff0f5d05503e21
  creationTimestamp: "2024-07-02T03:25:56Z"
  labels:
    app: larapod
  name: larapod
spec:
  containers:
  - args:
    - mysqld
    env:
    - name: MYSQL_ROOT_PASSWORD
      value: root_password
    - name: MYSQL_DATABASE
      value: laravel_db
    - name: MYSQL_USER
      value: laravel_user
    - name: MYSQL_PASSWORD
      value: laravel_password
    image: docker.io/library/mysql:8.0
    name: mysqlcontainer
    ports:
    - containerPort: 80
      hostPort: 8000
    - containerPort: 443
      hostPort: 4430
    - containerPort: 3306
      hostPort: 33060
    - containerPort: 5173
      hostPort: 5173
    - containerPort: 6379
      hostPort: 6379
    - containerPort: 8025
      hostPort: 8025
    volumeMounts:
    - mountPath: /var/lib/mysql
      name: aee287c71c2f145f4f8eae1f8f396719cb57d6fd85086cde2491aa359fc703c5-pvc
  - image: docker.io/axllent/mailpit:latest
    name: mailpitcontainer
  - args:
    - php-fpm
    image: my-php-fpm:latest
    name: phpcontainer
    volumeMounts:
    - mountPath: /var/www/html
      name: home-searchsam-Documentos-credits-backend-api-host-0
  - args:
    - nginx
    - -g
    - daemon off;
    image: my-nginx:latest
    name: nginxcontainer
    volumeMounts:
    - mountPath: /var/www/html
      name: home-searchsam-Documentos-credits-backend-api-host-0
  volumes:
  - name: aee287c71c2f145f4f8eae1f8f396719cb57d6fd85086cde2491aa359fc703c5-pvc
    persistentVolumeClaim:
      claimName: aee287c71c2f145f4f8eae1f8f396719cb57d6fd85086cde2491aa359fc703c5
  - hostPath:
      path: /home/searchsam/Documentos/credits-backend-api
      type: Directory
    name: home-searchsam-Documentos-credits-backend-api-host-0
